"""add trailer_video_id

Revision ID: ce169a139e2f
Revises: 28ab968b36a7
Create Date: 2026-09-09 23:20:48.678814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce169a139e2f'
down_revision = '28ab968b36a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('trailer_video_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'trailer_video_id')
    # ### end Alembic commands ###
